### ISSUE TITLE
Upload

### ISSUE THREAD

**Issue by Iquaridys** [Athlon1600/ie_proxy#1]
Hi like your project,
can you reupload Nova Proxy-Suite

https://www.proxynova.com/proxy-software/

for Internet Proxy Switcher is 3.2 but forNova Proxy-Suite
the link is 2,1 but new version 3.2, can you upload it again i like it

thanks

**Comment by Athlon1600** [comment]
> but for Nova Proxy-Suite the link is 2,1 but new version 3.2

that's actually just a typo on that page. 2.1 IS the latest version for Nova Proxy Suite. Version 3.2 for nova proxy suite doesn't exist.
